require './model/news'
require './model/replier'
require './model/user'
require './model/whether'
require './model/city'
require './model/battle_choice'
require './model/brain'
require './model/fight'
