default: &default
  adapter: postgresql
  username: root


development:
  <<: *default
  database: line_bot_development
  adapter: postgresql
  host: localhost
  username: root
  encoding: utf8
  pool: 5

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
